name_mapping = { 
    "Party": "Party Balloons",          # Legendaries
    "Lovesick": "Lovesick Bow",
    "Spooky": "Spooky Brew",
    "Slice": "Pumpkin Slice",
    "Dev": "Devilish Candle",
    "Gothic": "Gothic Bouquet",
    "Blossom": "Cherry Blossom Tree",
    "Icecream": "Icecream Mix",
    "Batwing": "Batwing Basher",
    "DVB": "Devilborn",
    "Hollow": "Hollow Scythe",
    "Jello": "Jello Dessert",
    "Cranberry": "Cranberry Barrel",
    "S. Reindeer": "Santa's Reindeer",
    "DB": "Dark Bone Crusher",
    "Merry": "Merry Music Box",
    "Classic": "Classic",
    "Soulless": "Soulless Theater",
    "Twisted": "Twisted Passion",
    "S. World": "Spring World",
    "Pegasus": "Pegasus Blade",
    "P. Chainsaw": "Psycho's Chainsaw",
    "Acidic": "Acidic Potions",
    "Paranormal": "Paranormal Hot Balloon",
    "Bloodthirst": "Bloodthirst Axe",
    "Strawberry": "Strawberry Jelly Basket",
    "Sand Castle": "Sand Castle",
    "Egg": "Easter Basket",
    "Marine": "Marine Anchor",
    "Lemon": "Bitter Lemonade Basket",
    "Blueberry": "Blueberry Jam Basket",
    "Pristine": "Pristine Chocolatery",
    "Yuletide": "Yuletide Gift",
    "Bleeding": "Bleeding Heart",
    "Lunar": "Lunar Scepter",
    "Grim": "Grim Galleon",
    "Rage": "Ragebringer",
    "Thorns": "Blade of Thorns",
    "Pot": "Pot O' Gold",
    "Phantom": "Phantom Light",
    "Piñata": "Piñata",
    "Turkey": "Roasted Turkey",
    "Autumn Tent": "Autumn Tent",
    "DM": "Dark Mansion",
    "Clock": "Grandfather Clock",
    "Fiery": "Fiery Phoenix",
    "Scarecrow": "Autumn Scarecrow",
    "Jollyday": "Jollyday Batter",
    "Candelabra": "Festive Candelabra",
    "LB": "Light Bone Crusher",
    "Chick": "Easter Chick",
    "Midnight": "Midnight Light",
    "Luxury": "Luxury Projector",
    "Viper": "Jade Viper",
    "Drums": "Marching Drums",
    "Witch": "Witch Hunter",
    "Warlock": "Warlock Hunter",
    "Alchemist": "Alchemist Hunter",
    "Magical Portal": "Magical Portal",
    "Coffin": "Coffin",
    "Tombstone": "Tombstone Bash",
    "Mothership": "Mothership",
    "Abolisher": "Aurora Abolisher",
    "G. Firework": "Golden Firework",
    "Hotline": "Holiday Hotline",
    "Santa's Sleigh": "Santa's Sleigh",
    "Toy Box": "Toy Box",
    "Doom": "Doomthrust",
    "Frost": "Frost Engine",
    "2nd": "2nd Anniversary",
    "Lilium": "Lilium Bush",
    "M. Trident": "Mystical Trident",
    "Anc. Trident": "Ancient Trident",
    "Ancs. Trident": "Ancestral Trident",
    "Fortune": "Fortune House",
    "Lucky": "Lucky Top Hat",
    "Cocoa Maker": "Cocoa Machine",
    "Red NC": "Red Nutcracker",
    "CCJ": "Candy Cane Jar",
    "Snow Globe": "Snow Globe",
    "Snowman": "Snowman",
    "Lil Tree": "Lil' Tree",
    "Fish Tank": "Fish Tank",
    "BLM": "Black Light Madness",
    "Dave": "Dave Pumpkins",
    "Cursed Tent": "Cursed Circus Tent",
    "Haunted Tent": "Haunted Circus Tent",
    "Ench. Tent": "Enchanted Circus Tent",
    "C. Broom": "Celestial Witch Broom",
    "L. Broom": "Lunar Witch Broom",
    "S. Broom": "Solar Witch Broom",
    "Moon Staff": "Moon Staff",
    "Santa Boot": "Santa Boot",
    "Toy Santa": "Toy Santa",
    "2019": "2019",
    "S. Chimney": "Santa Chimney",
    "Blue NC": "Blue Nutcracker",
    "Toy Elf": "Toy Elf",
    "3rd": "3rd Anniversary",
    "1 Billion": "1 Billion",
    "2020": "2020",
    "Beast": "Unleashed Beast",
    "Nightbloom": "Nightbloom",
    "Dayflower": "Dayflower",
    "BoF": "Book of Fortunes",
    "Owl Tree": "Owl Tree",
    "Chromatic": "Chromatic Phoenix",
    "Festive Train": "Festive Train",
    "Winter Train": "Winter Train",
    "Sweet Train": "Sweet Train",
    "Ice Sleigh": "Ice Sleigh",
    "SoP": "Stack of Presents",
    "Gingerhouse": "Gingerbread House",
    "Eggnog Maker": "Eggnog Machine",
    "Watering": "Watering Can",
    "Honey Tree": "Honey Hive Tree",
    "Crops": "Autumn Crops",
    "Cozy Cocoa": "Cozy Cocoa",
    "W. Breeze": "Winter Breeze",
    "Krampus": "Krampus Chimney",
    "Jingle Bells": "Jingle Bells",
    "Pinecone": "Festive Pinecone",
    "Permafrost": "Permafrost Axe",
    "Snowboarder": "Snowboarder Penguin",
    "Blizzaria": "Eye of Blizzaria",
    "Grape": "Grape Barrel",
    "F. Fruitcake": "Festive Fruitcake",
    "Sweethearts": "Sweethearts Store",
    "Fountain": "Flourished Fountain",
    "Lamp": "Autumn Lamp",
    "Cornucopia": "Cornucopia",
    "4th": "4th Anniversary",
    "5th": "5th Anniversary",
    "6th": "6th Anniversary",
    "2021": "2021",
    "2022": "2022",
    "2023": "2023",
    "Vintage TV": "Vintage TV",
    "Circus Cage": "Circus Cage",
    "Deathberry": "Deathberry Pie",
    "Spookpumpkin": "Spookpumpkin Pie",
    "Scareapple": "Scareapple Pie",
    "Snowman Box": "Snowman Box",
    "Santa Box": "Santa Box",
    "Elf Box": "Elf Box",
    "Frequency": "Frosted Frequency",
    "Frozen F.": "Frozen Fortress",
    "Frostbite": "Frostbite",
    "S. Firework": "Scarlet Firework",
    "Mycelium": "Mycelium Mallet",
    "Fungal": "Fungal Thumper",
    "Shroomy": "Shroomy Smasher",
    "2024": "2024",
    "2025": "2025",
    "Fairy Tale": "Fairy Tale Book",
    "Irish Harp": "Irish Harp",
    "Ancient Portal": "Ancient Portal",
    "Cuddly Bunny": "Cuddly Bunny",
    "Fudge Bunny": "Fudge Bunny",
    "Tropical": "Tropical Drink",
    "Beach Boat": "Beach Boat",
    "Coastal": "Coastal Lighthouse",
    "Theatrical": "Theatrical Spotlight",
    "Canvas": "Paint Canvas",
    "Piano": "Antique Piano",
    "Bloodline": "Bloodline Bat",
    "Starborne": "Starborne Reverie",
    "Pharaoh": "Pharaoh Sarcophagus",
    "Zombie": "Zombie Hand",
    "Marshmallow": "Toasted Marshmallow",
    "Harvester": "Fall Harvester",
    "Wheelbarrow": "Fall Wheelbarrow",
    "VIP": "VIP Ban Hammer",
    "7th": "7th Anniversary",
    "8th": "8th Anniversary",
    "Leprechaun": "Leprechaun Boot",
    "5 Billion": "5 Billion",           
    "Lemonade Jar": "Lemonade Jar",         # Epics
    "Gumball": "Gumball Machine",
    "Vanillaberry": "Vanillaberry Cake",
    "Choco Dip": "Choco Dip",
    "Water Gun": "Water Gun",
    "P. Axe": "Psycho's Axe",
    "Ube Roll": "Ube Roll",
    "Caramel Roll": "Caramel Roll",
    "Friendly G.": "Friendly Ghosts",
    "Spooky Bats": "Spooky Bats",
    "Tomato Eater": "Tomato Eater Gopher",
    "Demon Blood": "Demon Blood",
    "Monster Blood": "Monster Blood",
    "C. Treats": "Chocolate Treats",
    "Candy Corn": "Candy Corn",
    "Gingerdolph": "Gingerdolph",
    "Fireworks": "Fireworks",
    "Red Sweater": "Red Sweater",
    "Sweet Present": "Sweet Present",
    "Teddy Bear": "Teddy Bear Present",
    "Polar Bear": "Polar Bear Present",
    "C. Voodoo": "Cursed Voodoo",
    "M. Voodoo": "Magical Voodoo",
    "Jade Chest": "Jade Chest",
    "Ruby Chest": "Ruby Chest",
    "Moonlit B.": "Moonlit Butterflies",
    "Sunlit B.": "Sunlit Butterflies",
    "Sweetcone": "Sweet Snowcone",
    "Sourcone": "Sour Snowcone",
    "F. Foliage": "Fall Foliage",
    "A. Foliage": "Autumn Foliage",
    "B. Mirror": "Broken Mirror",
    "C. Painting": "Cursed Painting",
    "Veggie Eater": "Veggie Eater Gopher",
    "Z. Brain Jar": "Zombie Brain Jar",
    "F. Brain Jar": "Frankenstein's Brain Jar",
    "G. Peppermint": "Green Peppermint",
    "Peppermint": {
        "Epic": "Peppermint gem",
        "Rare": "Peppermint"
    },
    "Fortress": "Forbidden Fortress",
    "Palace": "Princess Palace",
    "J. Mailbox": "Joyful Mailbox",
    "E. Mailbox": "Evergreen Mailbox",
    "Stratis": "Stratis",
    "Sweet Treats": "Sweet Treats",
    "Sour Treats": "Sour Treats",
    "Celestial": "Celestial",
    "Painting Roll": "Painting Roll",
    "Spraying Can": "Spraying Can",
    "L. Mocktail": "Lime Mocktail",
    "O. Mocktail": "Orange Mocktail",
    "Malicious T.": "Malicious Treat",
    "Spiteful T.": "Spiteful Treat",
    "Haybale": "Haybale",
    "Holly Berry": "Holly Berry",
    "Fruitcake": "Fruitcake",
    "Corruption": "Corruption",
    "Cash": "Cash",
    "PSW": "Pink Star Wrap",                   # Rares
    "BSW": "Blue Star Wrap",
    "Sour Candy": "Sour Candy",
    "Cotton Candy": "Cotton Candy",
    "Jellybean": "Jellybean Cake",
    "Bubble Tea": "Bubble Tea",
    "Scarf": "Scarf",
    "S. Night": "Scarlet Night",
    "Graveyard": "Graveyard",
    "H. Stars": "Halloween Stars",
    "Angry Spiders": "Angry Spiders",
    "Ireland": "Ireland Flag",
    "Blizzard": "Blizzard",
    "Flesh": "Flesh",
    "CnM": "Cookies N' Milk",
    "G. Cookies": "Ginger Cookies",
    "Santa's Letter": "Santa's Letter",
    "Galaxy Clouds": "Galaxy Clouds",
    "Lil' Devil": "Lil' Devil",
    "Midnight Sky": "Midnight Sky",
    "Pumpkin Sky": "Pumpkin Sky",
    "Emerald Sky": "Emerald Sky",
    "Winter Sky": "Winter Sky",
    "Mystical Night": "Mystical Night",
    "Reptile": "Reptile Skin",
    "Midnight Sea": "Midnight Sea",
    "Underwater": "Underwater Ocean",
    "Coral Reefs": "Coral Reefs",
    "Clown": "Clown",
    "H. Night": "Halloween Night",
    "Snowing": "Snowing",
    "Festive Dots": "Festive Dots Wrap",
    "Snowy Night": "Snowy Night Wrap",
    "Nebula": "Nebula",
    "Xeno": "Xeno",
    "Party Skulls": "Party Skulls",
    "Ghostly Night": "Ghostly Night",
    "Velvet Webs": "Velvet Webs",
    "S. Patches": "Scarecrow Patches",
    "Blue Flax": "Blue Flax",
    "Daisies": "Daisies",
    "Lilypads": "Lilypads",
    "QoH": "Queen of Hearts",
    "Dragon": "Dragon's Scales",
    "Fireflies": "Fireflies",
    "Slime": "Slime",
    "Blighted": "Blighted Flame",
    "Will O' Wisp": "Will O' Wisp",
    "Wheat Field": "Wheat Field",
    "Corn Crops": "Corn Crops",
    "Vineyard": "Vineyard",
    "Overseer": "Overseer",
    "Hellstone": "Hellstone",
    "Stained Webs": "Stained Web",
    "Mint": "Chocolate Mint",
    "Jolly Crimson": "Jolly Crimson",
    "Fruit Punch": "Fruit Punch",
    "Sugar Cookies": "Sugar Cookies",
    "Xmas Lights": "Christmas Lights",
    "Buables": "Baubles",
    "Secret Santa": "Secret Santa",
    "Joyous": "Joyous Wrap",
    "Scrooge": "Scrooge's Suit",
    "Nightmare": "Nightmare Shadow",
    "Lil Frosty": "Lil Frosty",
    "Festive Lights": "Festive Lights",
    "RSW": "Red Star Wrap",
    "Packed Snow": "Packed Snow",
    "Biotech": "Biotech",
    "Arts & Crafts": "Arts and Crafts",
    "Graffiti": "Graffiti",
    "Porcelain": "Porcelain",
    "Sunset": "Sunset Beach",
    "Seashore": "Seashore Shells",
    "Beach Waves": "Beach Waves",
    "Barn": "Barn",
    "Carrot Cake": "Carrot Cake",
    "Broadcast": "Barren Broadcast",
    "Blood Moon": "Blood Moon",
    "Analog Horror": "Analog Horror",
    "Sea Monster": "Sea Monster",
    "Bleak": "Bleak Ink",                          # Commons
    "Glowy Bush": "Glowy Bush",
    "Ghost": "Ghost",
    "Cherry": "Cherry Pie",
    "Vanilla": "Vanilla Brownie",
    "Aurora": "Aurora",
    "Dark Star": "Dark Star",
    "Pumpkin Star": "Pumpkin Star",
    "Toxic": "Toxic",
    "Cold Star": "Cold Star",
    "Storm Surge": "Storm Surge",
    "Energetic": "Energetic Poison",
    "R. Nose": "Rudolph's Nose",
    "Sprinkles": "Sprinkles",
    "Confetti": "Confetti",
    "Autumn Plaid": "Autumn Plaid",
    "Winter Plaid": "Winter Plaid",
    "Yule Log": "Yule Log",
    "Snow Pile": "Snow Pile",
    "Igloo": "Igloo",
    "Solar Stone": "Solar Stone",
    "Ocean Water": "Ocean Water",
    "Ectoplasm": "Ectoplasm",
    "Pixel Xmas": "Pixel Christmas",
    "Eggnog": "Eggnog",
    "Snowy Forest": "Snowy Forest",
    "Frosted": "Frosted",
    "Tidal Waves": "Tidal Waves",
    "Clownfish": "Clownfish",
    "Pirate": "Pirate",
    "Heat Core": "Heat Core",
    "Bio Core": "Bio Core",
    "Ice Core": "Ice Core",
    "S. Potion": "Spooky Potion",
    "Chocolate Bar": "Chocolate Bar",
    "Bones": "Bones",
    "Black Cat": "Black Cat",
    "Dark Devil": "Dark Devil",
    "Trick": "Trick or Treat",
    "Mummy": "Mummy Bandages",
    "Spring Plaid": "Spring Plaid",
    "Jam": "Strawberries",
    "Unicorn": "Unicorn Starlight",
    "Beanstalk": "Beanstalk",
    "Neon Black": "Neon Black",
    "Neon Pink": "Neon Pink",
    "Neon Orange": "Neon Orange",
    "Neon Green": "Neon Green",
    "Monster Scars": "Monster Scars",
    "Winter Dusk": "Winter Dusk",
    "Bewitched": "Bewitched",
    "N. Coal": "Nightmare Coal",
    "Iceberg": "Iceberg",
    "Chimney": "Chimney",
    "Wreath": "Wreath",
    "Black & White": "Black and White",
    "Midpumpkin": "Midnight Pumpkin",
    "Pumpkin": "Pumpkin",
    "Ice": "Ice",
    "Frosty's Mallet": "Frosty's Mallet",
    "Santa's Mallet": "Santa's Mallet",
    "Elf's Mallet": "Elf's Mallet",
    "Green Knitted": "Green Knitted",
    "Red Knitted": "Red Knitted",
    "White Knitted": "White Knitted",
    "Plasma Core": "Plasma Core",
    "Night Snail": "Night Snail",
    "Garden Snail": "Garden Snail",
    "Tulips": "Tulips",
    "Sunflowers": "Sunflowers",
    "Starry Sky": "Starry Sky",
    "M. Mushroom": "Magic Mushroom",
    "Vibrant": "Vibrant Leaves",
    "Haystack": "Haystack",
    "Latte": "Cinnamon Latte",
    "Acorns": "Leaves N' Acorns",
    "Mr Lunatic": "Mr Lunatic",
    "Crescent": "Crescent Moon",
    "M. Spider": "Magical Spider",
    "Cave Monster": "Cave Monster",
    "Candy Egg": "Candy Egg",
    "S. Window": "Snowy Village",
    "Cinder Gift": "Cinder Gift",
    "December's": "December's Duality",
    "Red Velvet": "Red Velvet",
    "Winter Swirl": "Winter Swirl",
    "Hot Cocoa": "Hot Cocoa",
    "Yeti": "Yeti",
    "Xmas Cracker": "Christmas Cracker",
    "Winterly": "Winterly Night",
    "Winter Wind": "Winter Wind",
    "P. Bark": "Peppermint Bark",
    "Xmas Biscuits": "Christmas Biscuits",
    "Music Sheet": "Music Sheet",
    "Movie Reels": "Movie Reel",
    "Portrait Wall": "Portrait Wall",
    "Camera": "Camera",
    "Summer Plaid": "Summer Plaid",
    "Popsicle": "Popsicle",
    "Watermelon": "Watermelon",
    "Neapolitan": "Neapolitan",
    "Stage Fright": "Stage Fright",
    "Vampiric": "Vampiric Corset",
    "Drac's Castle": "Dracula's Castle",
    "Werewolf": "Werewolf",
}

# Total items in mapping
print(f"Total items in name_mapping: {len(name_mapping) + 1}")
